# Generated by Django 3.2 on 2022-07-26 05:17

from django.db import migrations


def calculate_order_items(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')

    for order in Order.objects.all():
        if not order.items:
            for product in order.products:
                OrderItem.objects.create(
                    product = product,
                    order = order,
                    price = product.price,
                    quantity = product.quantity,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20220726_1108'),
    ]

    operations = [
        migrations.RunPython(calculate_order_items),
    ]
