# Generated by Django 3.2 on 2022-08-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20220726_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Необработанный'), ('2', 'В сборке'), ('3', 'Передан в доставку'), ('4', 'Завершен')], default='1', max_length=50, verbose_name='Статус'),
        ),
    ]
