# Generated by Django 3.2 on 2022-08-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Необработанный'), ('2', 'В сборке'), ('3', 'Передан в доставку'), ('4', 'Завершен')], db_index=True, default='1', max_length=50, verbose_name='Статус'),
        ),
    ]
