# Generated by Django 3.2 on 2022-08-08 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preparing_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='foodcartapp.restaurant', verbose_name='Готовит ресторан:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('1', 'Не выбрано'), ('2', 'Наличными'), ('3', 'Электронно')], db_index=True, default='1', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
