# Generated by Django 3.2 on 2022-08-09 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='Адрес')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('geocoder_req_date', models.DateTimeField(default=datetime.datetime(2022, 8, 9, 16, 42, 35, 262241, tzinfo=utc), verbose_name='Дата последнего запроса к геокодеру')),
            ],
        ),
    ]
