# Generated by Django 3.2 on 2022-08-09 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geocoder_req_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего запроса к геокодеру'),
        ),
    ]
